# Generated by Django 5.1.3 on 2024-11-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order_session_id_order_track_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('En Proceso', 'En Proceso'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], default='Recibido', max_length=20),
        ),
    ]
