# Generated by Django 5.1.3 on 2024-11-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash on Delivery', 'Cash on Delivery')], default='Card', max_length=20),
        ),
    ]
